[build]
  command = "npm run netlify-build"
  publish = "out"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

# Explicitly set production branch to 'main'
[context.production]
  base = "/"
  publish = "out"
  command = "npm run netlify-build"

[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# No need for redirects with static export
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  included_files = ["content/**"] 