[build]
  command = "npm run netlify:static"
  publish = "out"
  base = "/"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false --legacy-peer-deps"
  SKIP_INSTALL_DEPS = "false"
  NETLIFY_USE_YARN = "false"
  NEXT_PUBLIC_SITE_URL = "https://willowy-mochi-145885.netlify.app"
  NEXT_PUBLIC_BASE_PATH = ""
  NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY_CONTEXT = "production"
  NEXT_PUBLIC_DEFAULT_LOCALE = "ar"
  NEXT_PUBLIC_DOMAIN = "willowy-mochi-145885.netlify.app"
  ROLLUP_EXTERNAL = "url"
  NEXT_PUBLIC_USE_WEBP_ONLY = "true"

# Explicitly set production branch to 'main'
[context.production]
  base = "/"
  publish = "out"
  command = "npm run netlify:static"

[context.production.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false --legacy-peer-deps"
  NEXT_PUBLIC_SITE_URL = "https://willowy-mochi-145885.netlify.app"
  NEXT_PUBLIC_BASE_PATH = ""
  NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY_CONTEXT = "production"
  NEXT_PUBLIC_DEFAULT_LOCALE = "ar"
  NEXT_PUBLIC_DOMAIN = "willowy-mochi-145885.netlify.app"
  NEXT_PUBLIC_USE_WEBP_ONLY = "true"

# Headers for static files
[[headers]]
  for = "/webp/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA Fallback - uncomment if needed for client-side routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[functions]
  included_files = ["content/**"]

# Configure build to skip TypeScript errors in dev dependencies
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true 