/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://fakhrkhaleej.com',
  generateRobotsTxt: true,
  exclude: [
    '/testimonials',
    '/services/education',
    '/services/hospitality',
    '/services/security',
    '/services/aviation',
    '/services/government',
    '/services/healthcare',
    '/services/industrial',
    '/blog/uniform-management-systems-for-saudi-hospitals-and-clinics',
    '/blog/protective-integration-architecture-advanced-safety-systems-for-saudi-emergency-medical-personnel-2025',
    '/blog/chef-whites-and-kitchen-staff-uniforms-for-saudi-arabias-culinary-industry',
    '/blog/high-visibility-uniforms-for-public-works-employees-in-saudi-cities',
    '/blog/chromatic-experience-architecture-advanced-color-systems-for-saudi-hospitality-environments-2025',
    '/blog/lab-coats-material-choices-and-safety-standards-for-saudi-laboratories',
    '/blog/cultural-identity-integration-architecture-advanced-heritage-systems-for-saudi-hospitality-attire-2025',
    '/blog/maternity-scrubs-and-uniform-options-for-healthcare-professionals',
    '/blog/multimodal-utility-integration-systems-advanced-garment-frameworks-for-hospitality-service-optimization-2025',
    '/blog/laundry-and-maintenance-contracts-for-large-government-departments',
    '/blog/headwear-etiquette-and-options-within-saudi-government-uniform-policy',
    '/blog/balancing-tradition-and-modernity-in-official-ksa-attire',
    '/blog/perception-enhancement-architecture-advanced-design-systems-for-hospitality-brand-projection-2025',
    '/blog/antimicrobial-fabrics-in-healthcare-uniforms-benefits-and-limitations',
    '/blog/color-psychology-in-designing-trustworthy-government-uniforms',
    '/blog/custom-tailoring-vs-standard-sizing-for-government-personnel',
    '/blog/how-professional-uniforms-influence-patient-trust-and-confidence-in-saudi-healthcare',
    '/blog/maintaining-professionalism-the-importance-of-well-maintained-government-uniforms',
    '/blog/uniform-requirements-for-specific-roles-in-government',
    '/blog/ordering-and-sizing-healthcare-uniforms-for-diverse-staff-bodies',
    '/blog/case-study-updating-uniforms-for-a-major-saudi-ministry',
    '/blog/custom-embroidery-for-hospital-logos-and-department-names',
    '/blog/identity-integration-systems-advanced-customization-frameworks-for-organizational-attire-2025',
    '/blog/footwear-regulations-for-government-uniforms-in-ksa',
    '/blog/patient-gowns-in-ksa-balancing-comfort-dignity-and-hygiene',
    '/blog/aviation-uniform-care-maintenance-guide',
    '/blog/ranking-insignia-and-badges-on-saudi-government-uniforms',
    '/blog/uniform-management-solutions-for-hospitals-leasing-vs-buying-in-ksa',
    '/blog/fluid-resistant-and-barrier-technologies-in-medical-textiles'
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        disallow: [
          '/testimonials',
          '/services/education',
          '/services/hospitality',
          '/services/security',
          '/services/aviation',
          '/services/government',
          '/services/healthcare',
          '/services/industrial',
          '/blog/uniform-management-systems-for-saudi-hospitals-and-clinics',
          '/blog/protective-integration-architecture-advanced-safety-systems-for-saudi-emergency-medical-personnel-2025',
          '/blog/chef-whites-and-kitchen-staff-uniforms-for-saudi-arabias-culinary-industry',
          '/blog/high-visibility-uniforms-for-public-works-employees-in-saudi-cities',
          '/blog/chromatic-experience-architecture-advanced-color-systems-for-saudi-hospitality-environments-2025',
          '/blog/lab-coats-material-choices-and-safety-standards-for-saudi-laboratories',
          '/blog/cultural-identity-integration-architecture-advanced-heritage-systems-for-saudi-hospitality-attire-2025',
          '/blog/maternity-scrubs-and-uniform-options-for-healthcare-professionals',
          '/blog/multimodal-utility-integration-systems-advanced-garment-frameworks-for-hospitality-service-optimization-2025',
          '/blog/laundry-and-maintenance-contracts-for-large-government-departments',
          '/blog/headwear-etiquette-and-options-within-saudi-government-uniform-policy',
          '/blog/balancing-tradition-and-modernity-in-official-ksa-attire',
          '/blog/perception-enhancement-architecture-advanced-design-systems-for-hospitality-brand-projection-2025',
          '/blog/antimicrobial-fabrics-in-healthcare-uniforms-benefits-and-limitations',
          '/blog/color-psychology-in-designing-trustworthy-government-uniforms',
          '/blog/custom-tailoring-vs-standard-sizing-for-government-personnel',
          '/blog/how-professional-uniforms-influence-patient-trust-and-confidence-in-saudi-healthcare',
          '/blog/maintaining-professionalism-the-importance-of-well-maintained-government-uniforms',
          '/blog/uniform-requirements-for-specific-roles-in-government',
          '/blog/ordering-and-sizing-healthcare-uniforms-for-diverse-staff-bodies',
          '/blog/case-study-updating-uniforms-for-a-major-saudi-ministry',
          '/blog/custom-embroidery-for-hospital-logos-and-department-names',
          '/blog/identity-integration-systems-advanced-customization-frameworks-for-organizational-attire-2025',
          '/blog/footwear-regulations-for-government-uniforms-in-ksa',
          '/blog/patient-gowns-in-ksa-balancing-comfort-dignity-and-hygiene',
          '/blog/aviation-uniform-care-maintenance-guide',
          '/blog/ranking-insignia-and-badges-on-saudi-government-uniforms',
          '/blog/uniform-management-solutions-for-hospitals-leasing-vs-buying-in-ksa',
          '/blog/fluid-resistant-and-barrier-technologies-in-medical-textiles'
        ],
      },
    ],
  },
  generateIndexSitemap: true,
  outDir: 'public',
  changefreq: 'weekly',
  priority: 0.7,
} 